package com.arion.dao;

import com.arion.model.SecurityReport;
import com.arion.util.DatabaseConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class SecurityReportsDAO {
    
    // Create - Add new report
    public int addReport(SecurityReport report) {
        String sql = "INSERT INTO security_reports (report_name, report_type, report_date, " +
                     "status, content, generated_by, notes) " +
                     "VALUES (?, ?, ?, ?, ?, ?, ?)";
        
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            
            System.out.println("[SecurityReportDAO] Adding report: " + report.getReportName());
            
            pstmt.setString(1, report.getReportName());
            pstmt.setString(2, report.getReportType());
            pstmt.setDate(3, new java.sql.Date(report.getReportDate().getTime()));
            pstmt.setString(4, report.getStatus());
            pstmt.setString(5, report.getContent());
            pstmt.setInt(6, report.getGeneratedBy());
            pstmt.setString(7, report.getNotes());
            
            int rowsAffected = pstmt.executeUpdate();
            
            if (rowsAffected > 0) {
                ResultSet rs = pstmt.getGeneratedKeys();
                if (rs.next()) {
                    int reportId = rs.getInt(1);
                    System.out.println("[SecurityReportDAO] Report added with ID: " + reportId);
                    return reportId;
                }
            }
            
        } catch (SQLException e) {
            System.err.println("[SecurityReportDAO] Error adding report: " + e.getMessage());
            e.printStackTrace();
        }
        
        return -1;
    }
    
    // Read - Get report by ID
    public SecurityReport getReportById(int reportId) {
        String sql = "SELECT r.*, u.full_name as generator_name, u2.full_name as reviewer_name " +
                     "FROM security_reports r " +
                     "LEFT JOIN users u ON r.generated_by = u.user_id " +
                     "LEFT JOIN users u2 ON r.reviewed_by = u2.user_id " +
                     "WHERE r.report_id = ?";
        
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setInt(1, reportId);
            ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()) {
                return extractReportFromResultSet(rs);
            }
            
        } catch (SQLException e) {
            System.err.println("[SecurityReportDAO] Error getting report by ID: " + e.getMessage());
        }
        
        return null;
    }
    
    // Read - Get all reports
    public List<SecurityReport> getAllReports() {
        List<SecurityReport> reports = new ArrayList<>();
        String sql = "SELECT r.*, u.full_name as generator_name, u2.full_name as reviewer_name " +
                     "FROM security_reports r " +
                     "LEFT JOIN users u ON r.generated_by = u.user_id " +
                     "LEFT JOIN users u2 ON r.reviewed_by = u2.user_id " +
                     "ORDER BY r.created_date DESC";
        
        try (Connection conn = DatabaseConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            
            while (rs.next()) {
                reports.add(extractReportFromResultSet(rs));
            }
            
            System.out.println("[SecurityReportDAO] Retrieved " + reports.size() + " reports");
            
        } catch (SQLException e) {
            System.err.println("[SecurityReportDAO] Error getting all reports: " + e.getMessage());
        }
        
        return reports;
    }
    
    // Read - Get reports by user (generated by)
    public List<SecurityReport> getReportsByUser(int userId) {
        List<SecurityReport> reports = new ArrayList<>();
        String sql = "SELECT r.*, u.full_name as generator_name, u2.full_name as reviewer_name " +
                     "FROM security_reports r " +
                     "LEFT JOIN users u ON r.generated_by = u.user_id " +
                     "LEFT JOIN users u2 ON r.reviewed_by = u2.user_id " +
                     "WHERE r.generated_by = ? " +
                     "ORDER BY r.created_date DESC";
        
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setInt(1, userId);
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()) {
                reports.add(extractReportFromResultSet(rs));
            }
            
        } catch (SQLException e) {
            System.err.println("[SecurityReportDAO] Error getting reports by user: " + e.getMessage());
        }
        
        return reports;
    }
    
    // Read - Get reports by type
    public List<SecurityReport> getReportsByType(String reportType) {
        List<SecurityReport> reports = new ArrayList<>();
        String sql = "SELECT r.*, u.full_name as generator_name, u2.full_name as reviewer_name " +
                     "FROM security_reports r " +
                     "LEFT JOIN users u ON r.generated_by = u.user_id " +
                     "LEFT JOIN users u2 ON r.reviewed_by = u2.user_id " +
                     "WHERE r.report_type = ? " +
                     "ORDER BY r.created_date DESC";
        
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, reportType);
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()) {
                reports.add(extractReportFromResultSet(rs));
            }
            
        } catch (SQLException e) {
            System.err.println("[SecurityReportDAO] Error getting reports by type: " + e.getMessage());
        }
        
        return reports;
    }
    
    // Read - Get reports by status
    public List<SecurityReport> getReportsByStatus(String status) {
        List<SecurityReport> reports = new ArrayList<>();
        String sql = "SELECT r.*, u.full_name as generator_name, u2.full_name as reviewer_name " +
                     "FROM security_reports r " +
                     "LEFT JOIN users u ON r.generated_by = u.user_id " +
                     "LEFT JOIN users u2 ON r.reviewed_by = u2.user_id " +
                     "WHERE r.status = ? " +
                     "ORDER BY r.created_date DESC";
        
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, status);
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()) {
                reports.add(extractReportFromResultSet(rs));
            }
            
        } catch (SQLException e) {
            System.err.println("[SecurityReportDAO] Error getting reports by status: " + e.getMessage());
        }
        
        return reports;
    }
    
    // Read - Get recent reports (limit)
    public List<SecurityReport> getRecentReports(int limit) {
        List<SecurityReport> reports = new ArrayList<>();
        String sql = "SELECT r.*, u.full_name as generator_name, u2.full_name as reviewer_name " +
                     "FROM security_reports r " +
                     "LEFT JOIN users u ON r.generated_by = u.user_id " +
                     "LEFT JOIN users u2 ON r.reviewed_by = u2.user_id " +
                     "ORDER BY r.created_date DESC LIMIT ?";
        
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setInt(1, limit);
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()) {
                reports.add(extractReportFromResultSet(rs));
            }
            
        } catch (SQLException e) {
            System.err.println("[SecurityReportDAO] Error getting recent reports: " + e.getMessage());
        }
        
        return reports;
    }
    
    // Update - Update report status
    public boolean updateReportStatus(int reportId, String newStatus) {
        String sql = "UPDATE security_reports SET status = ? WHERE report_id = ?";
        
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, newStatus);
            pstmt.setInt(2, reportId);
            
            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
            
        } catch (SQLException e) {
            System.err.println("[SecurityReportDAO] Error updating report status: " + e.getMessage());
            return false;
        }
    }
    
    // Update - Mark as reviewed
    public boolean markAsReviewed(int reportId, int reviewedBy, String notes) {
        String sql = "UPDATE security_reports SET status = 'Reviewed', reviewed_by = ?, " +
                     "reviewed_date = CURRENT_TIMESTAMP, notes = ? WHERE report_id = ?";
        
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setInt(1, reviewedBy);
            pstmt.setString(2, notes);
            pstmt.setInt(3, reportId);
            
            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
            
        } catch (SQLException e) {
            System.err.println("[SecurityReportDAO] Error marking as reviewed: " + e.getMessage());
            return false;
        }
    }
    
    // Get report count
    public int getReportCount() {
        String sql = "SELECT COUNT(*) FROM security_reports";
        
        try (Connection conn = DatabaseConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            
            if (rs.next()) {
                return rs.getInt(1);
            }
            
        } catch (SQLException e) {
            System.err.println("[SecurityReportDAO] Error getting report count: " + e.getMessage());
        }
        
        return 0;
    }
    
    // Get count by status
    public int getReportCountByStatus(String status) {
        String sql = "SELECT COUNT(*) FROM security_reports WHERE status = ?";
        
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, status);
            ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()) {
                return rs.getInt(1);
            }
            
        } catch (SQLException e) {
            System.err.println("[SecurityReportDAO] Error getting count by status: " + e.getMessage());
        }
        
        return 0;
    }
    
    // Helper method to extract Report from ResultSet
    private SecurityReport extractReportFromResultSet(ResultSet rs) throws SQLException {
        SecurityReport report = new SecurityReport();
        report.setReportId(rs.getInt("report_id"));
        report.setReportName(rs.getString("report_name"));
        report.setReportType(rs.getString("report_type"));
        report.setReportDate(new java.util.Date(rs.getDate("report_date").getTime()));
        report.setStatus(rs.getString("status"));
        report.setContent(rs.getString("content"));
        report.setGeneratedBy(rs.getInt("generated_by"));
        report.setCreatedDate(rs.getTimestamp("created_date"));
        report.setNotes(rs.getString("notes"));
        
        // Reviewed fields (nullable)
        int reviewedBy = rs.getInt("reviewed_by");
        if (!rs.wasNull()) {
            report.setReviewedBy(reviewedBy);
        }
        
        Timestamp reviewedDate = rs.getTimestamp("reviewed_date");
        if (reviewedDate != null) {
            report.setReviewedDate(reviewedDate);
        }
        
        // Additional fields from JOINs
        report.setGeneratorName(rs.getString("generator_name"));
        report.setReviewerName(rs.getString("reviewer_name"));
        
        return report;
    }
}